name: Deploy to WordPress.org
on:
  release:
    types: [published]
jobs:
  tag:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@latest
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
