name: Asset update
on:
  push:
    branches:
    - main
jobs:
  main:
    name: Push to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - name: WordPress.org asset update
      uses: 10up/action-wordpress-plugin-asset-update@latest
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}